### ISSUE TITLE
Wired network is disconnected

### ISSUE THREAD

**Issue by Foxly1990** [pltanton/net_widgets#10]
Hi! I'm use awesome wm 4 and Arch Linux, netctl-auto. My wifi interface name "wlp7s0". When i do:
`net_wireless = net_widgets.wireless({interface = "wlp7s0"})`
I get 

> Wired network is disconnected

**Comment by pltanton** [comment]
Check output of `iw dev wlp7s0 link` and `ip addr show wlp7s0`. All what that widget do is parsing output of these two commands.

**Comment by Foxly1990** [comment]
Может по-русски? В общем, я проверил вывод `iw dev wlp7s0 link` и `ip addr show wlp7s0`. В первом случае не хватало прав доступа. Не беда, в /etc/sudoerc добавил правило, чтобы команда `iw` не запрашивала пароль при вводе `sudo`, поменял строчку в `wireless.lua`. Вторая команда выводится нормально. В любой случае, результат тот же... 

> Wired network is disconnected

**Comment by pltanton** [comment]
`awk 'NR==3 {printf \"%3.0f\" ,($3/70)*100}' /proc/net/wireless` ? Там должен быть уровень сигнала, может быть с `sysfs` проблемы?

**Comment by Foxly1990** [comment]
Короче, все эти команды только из под `sudo` выполняются, как следуют. Я сейчас попробую напердолить...
