### ISSUE TITLE
[question] How do you implement the separator?

### ISSUE THREAD

**Issue by fluller** [pltanton/net_widgets#16]
Thanks for share the net_widgets, and I found your separator looks nice, I wanna how to implement it?

**Comment by pltanton** [comment]
It is done, using cairo. Now you can find my implementation as part of lain library [here](https://github.com/copycat-killer/lain/blob/794f5d3220d7793f553b8313b1b71313615fb197/util/separators.lua). Some ugly usage examples you can find in copycats powerarrow and powerarrow-darker [themes](https://github.com/copycat-killer/awesome-copycats/tree/master/themes).

**Comment by fluller** [comment]
Thank you, I got it!
