### ISSUE TITLE
tail call issue

### ISSUE THREAD

**Issue by ghe** [pltanton/net_widgets#17]
netwidgets master: 82d1ecd

on ubuntu 17.04
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.1

Following the instructions in the README
when adding line
`net_wired` = net_widgets.indicator({interfaces={"eth1"}, timeout=5})`
at 129 in my rc.lua

```
/home/ghe/.config/awesome/net_widgets/indicator.lua:11: in function </home/gens/.config/awesome/net_widgets/indicator.lua:9>
        (tail call): ?
        /home/gens/.config/awesome/rc.lua:129: in main chunk
```

**Comment by sensiblepuffin** [comment]
Assuming you hadn't figured this out, I might have encountered the same issue as you. Right above that tail-call message (for me), was the following warning:

<code>wibox.widget.background has been renamed to wibox.container.background.</code>

Changing <code>wibox.widget.background</code> to <code>wibox.container.background</code> at <code>$HOME/.config/awesome/net_widgets/indicator.lua:11</code> fixed this issue for me.

**Comment by pltanton** [comment]
Unfortunately I'm not use awesome wm in favor to xmonad, so I can miss some API changes.

@sensiblepuffin is wibox api changed? If so feel free to create pull request.

**Comment by pltanton** [comment]
Great job. Thanks!
