### ISSUE TITLE
Error by hovering over widget

### ISSUE THREAD

**Issue by bgrt** [pltanton/net_widgets#21]
just adding the standard wifi widget to the systray causes the following error for me in wireless.lua:190:

attempt to concatenate a nil value (upvalue 'font')

could you imagine what's wrong here?

**Comment by pltanton** [comment]
`local font = args.font or beautiful.font` seems like you have no font value on beautiful, try to set `font` manually on widget initialization (`net_widgets.wireless({...blabla..., font = "your-font-name", ...blabla...}`).

**Comment by bgrt** [comment]
that worked! thank you
