### ISSUE TITLE
Theme used in screenshot

### ISSUE THREAD

**Issue by modk** [pltanton/net_widgets#23]
Hello,

sorry for abusing the issues but I could not find your email address in order to contact you.
In the README.md you show a screenshot of the net widget next to other widgets of a theme.
I like the theme as well as the other widgets. Could you tell me which theme and widget this is. I would like to include this into my own theme somehow.

Thank you and please feel free to close this "issue" immediately.

**Comment by pltanton** [comment]
As I remember it is modified https://github.com/lcpz/awesome-copycats powerarrow
